uptrader/testapp/urls.py
from django.urls import path, include

from . import views

app_name = "testapp"

extra_patterns = [
    path("<path:path>/<slug:slug>/<int:id>/", views.page, name="sub-page"),
    path("<slug:slug>/<int:id>/", views.page, name="page"),
]

urlpatterns = [
    path("", include(extra_patterns)),
    path("", views.index, name="index"),
]

uptrader/uptrader/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('testapp.urls')),
]

uptrader/testapp/models.py
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.


class Menu(MPTTModel):

    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, verbose_name="URL", db_index=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, db_index=True, related_name='children')

    class MPTTMeta:
        order_insertion_by = ['name']

    class Meta:
        verbose_name = "Menu"
        verbose_name_plural = "Menus"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        if self.parent:
            return reverse("testapp:sub-page", kwargs={"path": "/".join([item.slug for item in self.get_ancestors()]), "slug": self.slug, "id":self.pk})
        else:
            return reverse("testapp:page", kwargs={"slug": self.slug, "id":self.pk})

uptrader/testapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from .models import Menu
from django.views.generic import ListView


# Create your views here.
def index(request): 
    return render(request, 'testapp/base.html')


def page(request, slug, id, path=None):
    menu_name = Menu.objects.filter(slug=slug)
    context={"slug":slug, "name":menu_name, "id": id}
    if path:
        context.update({"path":path})
    return render(request, 'testapp/page.html', context)

class MenuListView(ListView):
    model = Menu
    template_name = "testapp/page.html"

uptrader/testapp/templates/testapp/base.html
{% load static %}
{% load sass_tags %}
{% load maintags %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% sass_src 'testapp/style.scss' %}" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300..700&display=swap" rel="stylesheet">
    <title>Django tree menu</title>
</head>
<body>
    <div class="wrapper">
        {% block header %}
            <header class="header">
                {% show_title 'Django tree menu'%}
                {% block breadcrumbs %}
                {% endblock breadcrumbs %}   
                {% block menu %}
                    <div class="header__menu-list">
                        <div class="header__menu menu">
                                {% draw_menu 'Menu1' %}
                        </div>
                        <div class="header__menu menu">              
                                {% draw_menu 'Menu2' %}
                        </div>    
                    </div>
                {% endblock menu %}
            </header>
        {% endblock header %}
    </div>       
</body>
</html>

uptrader/testapp/templates/testapp/breadcrumbs.html
<nav class="header__breadcrumbs breadcrumbs">
    <ol class="breadcrumbs__list">
        <li class="breadcrumbs__breadcrumb breadcrumb">
            <a class="breadcrumb__link" href="/">Main></a>
        </li> 
        {% for parent in menu.get_ancestors %}
            <li class="breadcrumbs__breadcrumb breadcrumb">
                <a class="breadcrumb__link" href={{parent.get_absolute_url}}>{{parent.name }}></a>
            </li>   
        {% endfor %}
        <li class="breadcrumbs__breadcrumb breadcrumb">
            <a class="breadcrumb__link" href={{menu.get_absolute_url}}>{{menu.name}}</a>
        </li>
    </ol>
</nav>

uptrader/testapp/templates/testapp/menu.html
{% load mptt_tags %}
{% load maintags %}

 
<ul class="menu__root">
    {% recursetree menu_list %}
        {% if  current_item.get_root == node.get_root %}
            <li class="menu__item_{{ current_item|active_class:node }}">
                
                    <a class="menu__link_{{ current_item|active_class:node }}" href="{{node.get_absolute_url}}">{{node.name}}</a>
                
                {% if not node.is_leaf_node and node.level < current_item.level|add:"1" and node not in current_item.get_siblings and node in current_item.get_family %}
                    <ul class="menu__children"> 
                        {{children}}
                    </ul>                            
                {% endif %}
            </li>
        {% else %}
            <li class="menu__item">        
                    <a class="menu__link" href="{{node.get_absolute_url}}">{{node.name}}</a>
            </li>
        {% endif %}
    {% endrecursetree %}
</ul>

uptrader/testapp/templates/testapp/page.html
{% extends 'testapp/base.html' %}
{% load maintags %}

{% block header %}
    <header class="header">
        {% show_title %}
        {% block breadcrumbs %}
            {% breadcrumb %} 
        {% endblock breadcrumbs %}
        {% block menu %}
            <div class="header__menu-list">
                <div class="header__menu menu">
                        {% draw_menu 'Menu1' %}
                </div>
                <div class="header__menu menu">              
                        {% draw_menu 'Menu2' %}
                </div>    
            </div>
        {% endblock menu %}
    </header>
{% endblock header %}

uptrader/testapp/templates/testapp/title.html
<h1 class="header__title">
    {{title}}
</h1>